- doc/mainpage.dox
- include/lsst/log/Log.h
- tests/logTest.cc
Added a series of LOGS macros which are going to replace LOGF macros
using the iostream-style formatting instead of boost::format. LOGF
macros are deprecated but kept until everyone (qserv) migrates their
code. Documentation and unit tests are updated.
> Add iostream-style formatting in log package (DM-3926)

- tests/logTest.py
When the test runs under nose the namespace is logTest and not
__name__
> Modify test to use __name__

- src/Log.cc
- tests/logTest.cc
- tests/logTest.py
Replaced thread_local with POSIX equivalent to avoid problems with
clang on OS X which does not support thread_local.
> Do not use thread_local on OS X (DM-5272)

- include/lsst/log/Log.h
- python/lsst/log/logLib.i
- src/Log.cc
Previously LOG4CXX was initialized at DSO loading time (at globals
initialization time) which caused issues with global destructors
ordering. This patch delays initialization until first actual use of
logging methods which partially resolves the issue (there are still
possible use cases when the problems can re-appear).
Also some cleanup to macros for efficiency and simplicity after recent
changes to Log class.
Re-applied previous commit from DM-6521 - "Replace defaultLogger by a static method getDefaultLogger()"
> Delaying LOG4CXX initialization until first actual use (DM-6989)

- .gitignore
- examples/mp.py
- python/lsst/log/log.py
- python/lsst/log/logLib.i
- tests/logTest.cc
- tests/logTest.py
Also some minor code cleanups.
> DM-7188: Enable unicode strings in swig interface on Python 2

- .gitignore
- python/lsst/log/log.py
- python/lsst/log/logLib.i
- tests/logTest.py
- tests/testLog.cc
- tests/testLog.py
The bugs are:
- If one logs a message with a string that contains %s
and no format arguments, an exception is raised
because % formatting is attempted
- If one logs a message with a string that contains %s
after formatting with data arguments that are provided
the system segfaults because Log.log is called
(which attempts formatting) instead of Log.logMsg
> DM-7509: Fix two bugs in handling strings with %s

- python/lsst/log/utils.py
Add a utility method for the usage with logger names prefixed with "TRACEn", where n=0-5, to indicate increasing verbosity, as described in [RFC-203](https://jira.lsstcorp.org/browse/RFC-203). (e.g. TRACE2.afw.math.convolve)
> DM-6985: Add a utility method traceSetAt for fine-level tracing

- include/lsst/log/Log.h
The basic configuration is ensured through the first call to the
default logger. Currently this may be bypassed if getLogger('nonRoot')
is called before a default logger is set.  Fix this by delegating
the private constructor to the default constructor.
> DM-7754: Ensure initialization is done before first use

- include/lsst/log/Log.h
- src/Log.cc
QServ was the only place whch used static logMsg(), this ticket changes
qserv code to use non-static version of that method so we can also
remove static methods completely.
> Remove static Log::log() and Log::logMsg() methods (DM-6978).

- doc/mainpage.dox
- include/lsst/log/Log.h
- src/Log.cc
- tests/testLog.py
Default message format changed to "loggername LEVEL: message" and
default logging level is set to INFO. I think I also managed to simplify
configuration process so it looks simpler now. Documentation is updated
to reflect all changes.
> Improve default log configuration (DM-7955)

- doc/mainpage.dox
- python/lsst/log/log.py
- python/lsst/log/logLib.i
- tests/testLog.py
- String formatting is only done on demand.
- Supports keyword args for format()
> Add str.format variants of all log output methods

- src/Log.cc
MDC::put(...) does not replace existing mapping, on has to remove it
explicitly first.
> Fix incorrect context info in logger output (DM-10623)

- tests/test_log.py
Renamed testLog.py to test_log.py and removed shebang line. In few cases expected logging output included script name, had to change those lines too.
> Add unit test for overwriting MDC (DM-10871)

- python/lsst/log/log/logContinued.py
inspect.stack() will go and read the source files, which introduces I/O
that we'd like to avoid in order to minimise overheads. We don't need
to read the source to get the function name, which can be grabbed from
the frame.
> DM-10608: Log: avoid use of inspect.stack()

- ups/log.cfg
We should not be linking against `libutils`.
> log depends on utils python not utils C++

- setup.cfg
This looks like a bug in pycodestyle or flake8. The lines are:
lines = [l.split(']')[-1].rstrip("\n") for l in f.readlines()]
reflines = [l for l in reference.split("\n") if l != ""]
and only the second line triggers the error in the `l` after the `if`.
Masking the error code for now whilst we work out whether the code
itself needs to change.
> Mask E741 with test_log.py

- python/lsst/log/log/logContinued.py
- tests/test_log.py
Do not use LogContext class in LogHandler implementation, it does not
handle all use cases correctly. Also fix message interpolation in emit()
method - message can be arbitrary Python object.
> DM-15201: Fix LogHandler class

- .gitignore
- python/lsst/log/log/logContinued.py
- tests/test_log.py
This only deals with the python messages.  C++ log messages will do what they always do.  This is implemented as a big class property on `lsst.log.Log`. The idea is that a test can turn this on in `setUp`, check that a log message was created, and then turn it off in `tearDown`.
> DM-17651: Allow lsst.log to forward to Python logging

- python/lsst/log/log/logContinued.py
- tests/test_log.py
Two methods for two-way translation are moved into a special new
"namespace" class to keep interfaces clean.
> DM-17741: Factor out code to convert between logging levels

- doc/mainpage.dox
- examples/mp.py
- include/lsst/log/Log.h
- python/lsst/log/log/log.cc
- python/lsst/log/log/logContinued.py
- src/Log.cc
- tests/testLog.cc
- tests/test_log.py
In addition there are few small improvements:
- initialization/configuration step is made thread safe, and less confusing
- Python `Log` class now supports `pickle` so it can work with `multiprocess`
- added `Log.getChild` method to make it look more like Pylon `logging` logger, this is also a better replacement for hierarchical "context" management if someone needs that
> DM-17874: Remove ContextLog class and related code

- doc/mainpage.dox
- include/lsst/log/Log.h
- src/Log.cc
- tests/testLog.cc
Implement scope guard for logging MDC.
This small addition to log package is needed to support scope-based MDC control in qserv. It could be useful for other clients too.
> DM-21043: Qserv log diet: use named context for query ID

- python/lsst/log/__init__.py
- python/lsst/log/utils.py
- tests/test_redir.py
This allows log output to go to Jupyter notebook cells.
> DM-15361: Enable logging to Python streams.

- .github/workflows/cmake.yaml
- CMakeLists.txt
- python/lsst/log/CMakeLists.txt
- python/lsst/log/log/CMakeLists.txt
- python/lsst/log/version.cmake
- src/CMakeLists.txt
- tests/CMakeLists.txt
- tests/testLog.cc
- ups/log.table
Adds ability to build package with CMake in addition to eupspkg (allows to be included as submodule in other CMake projects, e.g. Qserv.)
> Add cmake support

- .github/workflows/cmake.yaml
- README.rst
- doc/conf.py
- setup.cfg
Updates based on the latest updates in the package template (https://github.com/lsst/templates/tree/master/project_templates/stack_package)
- Add a basic README
- Update doc/conf.py for the documenteer 0.6 Sphinx configuration API
> DM-30015: Update Sphinx conf.py for documenteer 0.6

- doc/mainpage.dox
- python/lsst/log/log/logContinued.py
- tests/test_log.py
Previously we only removed the f-string variants
that were explicitly marked deprecated but not the forwarders.
> DM-37534: Remove other f-string variants

- tests/test_log.py
- tests/test_redir.py
This reverts commit 5843a172e0115e7c6cde829fc557313077ea9058.
Turns out that we don't really support unicode in log unless we are using a fairly modern linux system.
> DM-45284: Do not test unicode since it doesn't work on Jenkins
